### ISSUE TITLE
Review code needed

### ISSUE THREAD

**Issue by BernierMaxence** [PolytechLyon/tp-mvc-chabrier-bernier-tp6#1]
Bonsoir @k33g, 

Nous sommes désolées pour le retard de ce rendu, concentrés sur les partiels à venir, nous avons manqué le jour de rendu (hier si nos souvenirs sont bons). 
Merci de votre compréhension, bonne fin journée :)

**Comment by k33g** [comment]
pas de soucis, je suis en retard aussi

**Comment by k33g** [comment]
@BernierMaxence toujours un plaisir de vous lire 👍
